### ISSUE TITLE
Expected object of scalar type Bool but got scalar type Byte

### ISSUE THREAD

**Issue by shunyooo** [shunyooo/kg-cvae-generator#1]
## 🐛 Bug

`main_eng.py`実行時、validationを行う際にエラー発生.

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/pdb.py", line 1701, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.7/pdb.py", line 1570, in _runscript
    self.run(statement)
  File "/usr/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/root/user/work/src/kg-cvae-generator/main_eng.py", line 15, in <module>
    """
  File "/root/user/work/src/kg-cvae-generator/main_eng.py", line 75, in main
    output_reports = cvae_trainer.experiment(train_loader, valid_loader, test_loader)
  File "/root/user/work/src/kg-cvae-generator/trainer/trainer.py", line 126, in experiment
    valid_output = self.valid(valid_data_loader, epoch=epoch)
  File "/root/user/work/src/kg-cvae-generator/trainer/trainer.py", line 196, in valid
    return self._run_one_epoch(self.valid_step, data_loader, "valid", epoch, False)
  File "/root/user/work/src/kg-cvae-generator/trainer/trainer.py", line 176, in _run_one_epoch
    step_output = step_function(model_input, current_step_num)
  File "/root/user/work/src/kg-cvae-generator/trainer/trainer.py", line 385, in valid_step
    model_output = self.model.forward(model_input)
  File "/root/user/work/src/kg-cvae-generator/model/cvae.py", line 621, in forward
    model_output = self.feed_train(feed_dict)
  File "/root/user/work/src/kg-cvae-generator/model/cvae.py", line 585, in feed_train
    decode_type='greedy')
  File "/root/user/work/src/kg-cvae-generator/model/decoder_fn_lib.py", line 72, in inference_loop
    done = (next_input_id == end_of_sequence_id) | done
RuntimeError: Expected object of scalar type Bool but got scalar type Byte for argument #2 'other' in call to _th_or
```

## 値のLog
pdbでの値確認

```
(Pdb) next_input_id
tensor([12750,  1275,  7650,  4080,  9690,  9690,  1275,  2805,  2295,  4080,
         4080,  7395,  9690, 16830, 10200,  8670,  9945,  9945,  9945,  1275,
         9690,  3060,  8670,  9690,  6120,  8670,  5865,  2805,  2550,  4080,
        24480,  9690, 20655,  4080,  9690,  4080,  9690,  9690,  4080,  9690,
         2040,  4080,  8670,  8670,  9945,  4080,  9945,  1275,  8670,  4080,
         4080,  4080,  9690,  4080,  8670,  4080,  1275,  5865,  9690, 31875],
       device='cuda:0')
```
```
(Pdb) end_of_sequence_id
3
```
```
(Pdb) (next_input_id == end_of_sequence_id)
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False],
       device='cuda:0')
```
```
(Pdb) done
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0',
       dtype=torch.uint8)
```

## Environment

```
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.0

Versions of relevant libraries:
[pip3] numpy==1.15.2
[pip3] torch==1.3.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.4.1
[conda] Could not collect
```

**Comment by shunyooo** [comment]
OR演算子をlong型に適用していたためおきたエラー。
▼ commit
071ddbd895d2b89424b7dcd77d1bb370a5dfae9c
